-- MySQL Script generated by MySQL Workbench
-- Fri Oct 26 23:34:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema equipe385145
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `equipe385145` ;

-- -----------------------------------------------------
-- Schema equipe385145
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `equipe385145` DEFAULT CHARACTER SET utf8 ;
USE `equipe385145` ;

-- -----------------------------------------------------
-- Table `autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autor` ;

CREATE TABLE IF NOT EXISTS `autor` (
  `nome` VARCHAR(60) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

CREATE TABLE IF NOT EXISTS `usuario` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `tipo` ENUM('aluno', 'professor', 'funcionario') NOT NULL,
  `senha` CHAR(64) NOT NULL,
  `permissao` ENUM('administrador', 'bibliotecario', 'usuario') NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso` ;

CREATE TABLE IF NOT EXISTS `curso` (
  `cod_curso` INT NOT NULL,
  `nome_curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aluno` ;

CREATE TABLE IF NOT EXISTS `aluno` (
  `matricula` INT NOT NULL,
  `data_de_conlusao_prevista` DATE NOT NULL,
  `data_de_ingresso` DATE NOT NULL,
  `cod_curso` INT NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `professor` ;

CREATE TABLE IF NOT EXISTS `professor` (
  `mat_siape` INT NOT NULL,
  `data_de_contratacao` DATE NOT NULL,
  `regime_trabalho` ENUM('20H', '40H', 'DE') NOT NULL,
  `cod_curso` INT NOT NULL,
  PRIMARY KEY (`mat_siape`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `funcionario` ;

CREATE TABLE IF NOT EXISTS `funcionario` (
  `matricula` INT NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telefones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telefones` ;

CREATE TABLE IF NOT EXISTS `telefones` (
  `matricula` INT NOT NULL,
  `numero` CHAR(11) NOT NULL,
  PRIMARY KEY (`matricula`, `numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categoria` ;

CREATE TABLE IF NOT EXISTS `categoria` (
  `cod_categoria` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livro` ;

CREATE TABLE IF NOT EXISTS `livro` (
  `isbn` CHAR(13) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `ano` INT NOT NULL,
  `editora` VARCHAR(45) NOT NULL,
  `qt_copias` INT NOT NULL,
  `cod_categoria` INT NOT NULL,
  PRIMARY KEY (`isbn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autor_livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autor_livro` ;

CREATE TABLE IF NOT EXISTS `autor_livro` (
  `autor_cpf` CHAR(11) NOT NULL,
  `livro_isbn` CHAR(13) NOT NULL,
  PRIMARY KEY (`autor_cpf`, `livro_isbn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprestimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emprestimo` ;

CREATE TABLE IF NOT EXISTS `emprestimo` (
  `matricula` INT NOT NULL,
  `isbn` CHAR(13) NOT NULL,
  `data_de_emprestimo` DATETIME NOT NULL,
  PRIMARY KEY (`matricula`, `isbn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserva` ;

CREATE TABLE IF NOT EXISTS `reserva` (
  `matricula` INT NOT NULL,
  `isbn` CHAR(13) NOT NULL,
  `data_de_reserva` DATETIME NOT NULL,
  PRIMARY KEY (`matricula`, `isbn`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `autor`
-- -----------------------------------------------------
START TRANSACTION;
USE `equipe385145`;
INSERT INTO `autor` (`nome`, `cpf`, `nacionalidade`) VALUES ('João Antônio', '12345678980', 'Brasileira');
INSERT INTO `autor` (`nome`, `cpf`, `nacionalidade`) VALUES ('Maria do rosário', '98765432199', 'Brasileira');
INSERT INTO `autor` (`nome`, `cpf`, `nacionalidade`) VALUES ('Raimundo Antônio', '85296374180', 'Brasileira');

COMMIT;


-- -----------------------------------------------------
-- Data for table `usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `equipe385145`;
INSERT INTO `usuario` (`matricula`, `nome`, `endereco`, `tipo`, `senha`, `permissao`) VALUES (389118, 'Samuel Hericles', 'Rua 22 de novembro,678,Marco', 'aluno', '1234', 'usuario');
INSERT INTO `usuario` (`matricula`, `nome`, `endereco`, `tipo`, `senha`, `permissao`) VALUES (392142, 'Manoel Vilela', 'Rua São José,563,Sobral', 'aluno', '1468', 'usuario');
INSERT INTO `usuario` (`matricula`, `nome`, `endereco`, `tipo`, `senha`, `permissao`) VALUES (385145, 'Gerônimo Perere', 'Rua Não sei, s/N, Itarema', 'aluno', '8921', 'usuario');

COMMIT;


-- -----------------------------------------------------
-- Data for table `curso`
-- -----------------------------------------------------
START TRANSACTION;
USE `equipe385145`;
INSERT INTO `curso` (`cod_curso`, `nome_curso`) VALUES (001, 'engenharia da computação');
INSERT INTO `curso` (`cod_curso`, `nome_curso`) VALUES (002, 'engenharia elétrica');
INSERT INTO `curso` (`cod_curso`, `nome_curso`) VALUES (003, 'psicologia');
INSERT INTO `curso` (`cod_curso`, `nome_curso`) VALUES (004, 'finanças');
INSERT INTO `curso` (`cod_curso`, `nome_curso`) VALUES (005, 'economia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `aluno`
-- -----------------------------------------------------
START TRANSACTION;
USE `equipe385145`;
INSERT INTO `aluno` (`matricula`, `data_de_conlusao_prevista`, `data_de_ingresso`, `cod_curso`) VALUES (389118, '2021-01-01', '2016-07-01', 001);
INSERT INTO `aluno` (`matricula`, `data_de_conlusao_prevista`, `data_de_ingresso`, `cod_curso`) VALUES (385145, '2021-01-01', '2016-08-02', 001);
INSERT INTO `aluno` (`matricula`, `data_de_conlusao_prevista`, `data_de_ingresso`, `cod_curso`) VALUES (398608, '2022-03-05', '2017-10-10', 002);

COMMIT;


-- -----------------------------------------------------
-- Data for table `professor`
-- -----------------------------------------------------
START TRANSACTION;
USE `equipe385145`;
INSERT INTO `professor` (`mat_siape`, `data_de_contratacao`, `regime_trabalho`, `cod_curso`) VALUES (400500, '2015-10-10', 'DE', 001);
INSERT INTO `professor` (`mat_siape`, `data_de_contratacao`, `regime_trabalho`, `cod_curso`) VALUES (400501, '2007-10-15', '40H', 002);
INSERT INTO `professor` (`mat_siape`, `data_de_contratacao`, `regime_trabalho`, `cod_curso`) VALUES (400101, '2006-08-15', '20H', 003);

COMMIT;


-- -----------------------------------------------------
-- Data for table `funcionario`
-- -----------------------------------------------------
START TRANSACTION;
USE `equipe385145`;
INSERT INTO `funcionario` (`matricula`) VALUES (400502);
INSERT INTO `funcionario` (`matricula`) VALUES (400503);
INSERT INTO `funcionario` (`matricula`) VALUES (389000);
INSERT INTO `funcionario` (`matricula`) VALUES (389001);

COMMIT;


-- -----------------------------------------------------
-- Data for table `telefones`
-- -----------------------------------------------------
START TRANSACTION;
USE `equipe385145`;
INSERT INTO `telefones` (`matricula`, `numero`) VALUES (400500, '88997502676');
INSERT INTO `telefones` (`matricula`, `numero`) VALUES (400501, '88997502667');
INSERT INTO `telefones` (`matricula`, `numero`) VALUES (400502, '88997502666');
INSERT INTO `telefones` (`matricula`, `numero`) VALUES (400503, '88997502677');

COMMIT;


-- -----------------------------------------------------
-- Data for table `categoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `equipe385145`;
INSERT INTO `categoria` (`cod_categoria`, `descricao`) VALUES (01, 'engenharia');
INSERT INTO `categoria` (`cod_categoria`, `descricao`) VALUES (02, 'psicologia');
INSERT INTO `categoria` (`cod_categoria`, `descricao`) VALUES (03, 'física');

COMMIT;


-- -----------------------------------------------------
-- Data for table `livro`
-- -----------------------------------------------------
START TRANSACTION;
USE `equipe385145`;
INSERT INTO `livro` (`isbn`, `titulo`, `ano`, `editora`, `qt_copias`, `cod_categoria`) VALUES ('978123456789', 'manual SIGGA UFC', 2018, 'UFC-Sobral', 100, 02);
INSERT INTO `livro` (`isbn`, `titulo`, `ano`, `editora`, `qt_copias`, `cod_categoria`) VALUES ('978852963741', 'Guia prático de sobrevivência na universidade', 1980, 'UFC-Central', 100, 01);
INSERT INTO `livro` (`isbn`, `titulo`, `ano`, `editora`, `qt_copias`, `cod_categoria`) VALUES ('978123456780', 'Banco de dados', 2008, 'UFC-Quixadá', 100, 03);

COMMIT;


-- -----------------------------------------------------
-- Data for table `autor_livro`
-- -----------------------------------------------------
START TRANSACTION;
USE `equipe385145`;
INSERT INTO `autor_livro` (`autor_cpf`, `livro_isbn`) VALUES ('12345678980', '978852963741');
INSERT INTO `autor_livro` (`autor_cpf`, `livro_isbn`) VALUES ('98765432199', '978852963452');
INSERT INTO `autor_livro` (`autor_cpf`, `livro_isbn`) VALUES ('85296374188', '\'978987654321');

COMMIT;


-- -----------------------------------------------------
-- Data for table `emprestimo`
-- -----------------------------------------------------
START TRANSACTION;
USE `equipe385145`;
INSERT INTO `emprestimo` (`matricula`, `isbn`, `data_de_emprestimo`) VALUES (400500, '978789456523', '2018-04-20');
INSERT INTO `emprestimo` (`matricula`, `isbn`, `data_de_emprestimo`) VALUES (389118, '978987654321', '2018-03-27');
INSERT INTO `emprestimo` (`matricula`, `isbn`, `data_de_emprestimo`) VALUES (394192 , '978789456123', '2000-01-01');

COMMIT;


-- -----------------------------------------------------
-- Data for table `reserva`
-- -----------------------------------------------------
START TRANSACTION;
USE `equipe385145`;
INSERT INTO `reserva` (`matricula`, `isbn`, `data_de_reserva`) VALUES (389118, '978987654321', '2018-01-10');
INSERT INTO `reserva` (`matricula`, `isbn`, `data_de_reserva`) VALUES (394192 , '978789456123', '2018-12-08');
INSERT INTO `reserva` (`matricula`, `isbn`, `data_de_reserva`) VALUES (385145, '97878945600', '2018-10-12');

COMMIT;

